# Generated by Django 4.1.6 on 2023-02-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cheeses'),
        ('catalogue', '0005_review_cheese'),
    ]

    operations = [
    ]
